### ISSUE TITLE
Landing Page Unresponsive on Mobile Devices

### ISSUE THREAD

**Issue by rudrathegreat** [Scratch-Client-4/landing#11]
When width is 750px, then tagline from below starts to creep up and the landing looks pretty disgusting. Also a sidenote, the down button is barely visible.

**Comment by micahlt** [comment]
Yep... Anyone want to deal with this?

**Comment by rudrathegreat** [comment]
I'll do it, I'll need to update the css files.

**Comment by rudrathegreat** [comment]
I have fixed the unresponsiveness, I am going to close this issue. If anyone finds any problems, then please reopen this issue and let me know!
