### ISSUE TITLE
Opening Animation Unnecessary

### ISSUE THREAD

**Issue by rudrathegreat** [Scratch-Client-4/landing#13]
This may seem counterintuitive, but i believe that the opening animation is unnescessary. The reason is because it makes it feel like the website is taking a long time to load, and that can make the user experience unsatisfying

**Comment by micahlt** [comment]
It does need to be shortened...

**Comment by githubfan** [comment]
Alright. Maybe we should adjust the length.

**Comment by rudrathegreat** [comment]
i mean eventually, people r going to get used to it, but most viewers will come to our website once and that's it and we want to leave a lasting impression on the viewer aka our audience

**Comment by rudrathegreat** [comment]
i'll make an update with a shortened opening animation, then will add it to the footer section branch, but for some reason i don't have write access to the files, which is weird

**Comment by micahlt** [comment]
Closing this issue.
