### ISSUE TITLE
404 NOT FOUND LANDING PAGE ERROR: URGENT!

### ISSUE THREAD

**Issue by rudrathegreat** [Scratch-Client-4/landing#19]
This is the error I experience on my windows laptop while testing the website - 

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: sfo1::rnlmc-1590640849257-0a35e52241d4
```
HELP REQUIRED!

**Comment by rudrathegreat** [comment]
Error fixed!

**Comment by micahlt** [comment]
@rudrathegreat This was an issue on my part, sorry xD
