### ISSUE TITLE
Spacing for "Our Team"

### ISSUE THREAD

**Issue by ConvexPolygon** [Scratch-Client-4/landing#4]
The spacing is off, and alternating colors don't work. This is a known issue, and I am working to fix it.

**Comment by micahlt** [comment]
Technically, this issue shouldn't be here because the pull request has not been merged.  If this issue is still there when the PR is approved, then we'll reopen this.

**Comment by ConvexPolygon** [comment]
Ik, but i'm still working on this and I didn't mean to submit the pull.
