### ISSUE TITLE
That tagline doesn't look right to me.

### ISSUE THREAD

**Issue by locness3** [Scratch-Client-4/landing#8]
@Scratch-Client-4/everyone what do you think of the landing page's tagline ? I find it weird, especially saying "interface" (maybe "apps" instead?)

**Comment by micahlt** [comment]
@locness3 Sounds good, I'll implement it in my next commit.

**Comment by rudrathegreat** [comment]
i totally agree with @locness3 it should be apps, but I understand why interfaces is being used there

**Comment by rudrathegreat** [comment]
I have edited the tagline from 'interfaces' to 'applications'. Let me know your thoughts on this move

**Comment by rudrathegreat** [comment]
I'm going to close this issue, reopen it if you want to!
